// @ts-ignore
import webExt from 'web-ext'
import path from 'path'
import fs from 'fs'

export interface LintResult {
  success: boolean
  errors: string[]
  warnings: string[]
}

/**
 * Runs web-ext lint on the specified directory.
 */
export async function lintExtension(sourceDir: string): Promise<LintResult> {
  try {
    const result = await webExt.cmd.lint(
      {
        sourceDir,
        selfHosted: true,
        output: 'none',
      },
      {
        shouldExitProgram: false,
      }
    )

    const errors: string[] = []
    const warnings: string[] = []

    if (result && result.errors) {
      result.errors.forEach((err: any) => {
        const msg = `${err.message} (${err.file || 'manifest.json'}:${err.line || 0})`
        if (err.level === 'error') {
          errors.push(msg)
        } else {
          warnings.push(msg)
        }
      })
    }

    return {
      success: errors.length === 0,
      errors,
      warnings,
    }
  } catch (error: any) {
    console.error('web-ext lint failed:', error)
    return {
      success: false,
      errors: [error.message || 'web-ext lint execution failed'],
      warnings: [],
    }
  }
}

/**
 * Runs web-ext build on the specified directory, saving the zip file in the outputDir.
 * Returns the absolute path of the generated zip file.
 */
export async function buildExtension(sourceDir: string, artifactsDir: string): Promise<string> {
  try {
    // Ensure artifacts directory exists
    fs.mkdirSync(artifactsDir, { recursive: true })

    const result = await webExt.cmd.build(
      {
        sourceDir,
        artifactsDir,
        overwriteDest: true,
      },
      {
        shouldExitProgram: false,
      }
    )

    // The result contains the absolute path to the extension zip file
    if (result && result.extensionZip) {
      return result.extensionZip
    }

    // Fallback search in artifactsDir if the property name differs
    const files = fs.readdirSync(artifactsDir)
    const zipFile = files.find((f) => f.endsWith('.zip'))
    if (zipFile) {
      return path.join(artifactsDir, zipFile)
    }

    throw new Error('No zip file was generated by web-ext build')
  } catch (error: any) {
    console.error('web-ext build failed:', error)
    throw new Error(`web-ext build failed: ${error.message}`)
  }
}
