// @ts-ignore
import webExt from 'web-ext'
import path from 'path'
import fs from 'fs'

export interface LintDiagnostic {
  code?: string
  message: string
  file: string
  line: number
  column: number
  level: 'error' | 'warning' | 'notice'
  description?: string
}

export interface DetailedLintResult {
  success: boolean
  errorsCount: number
  warningsCount: number
  diagnostics: LintDiagnostic[]
  errors: string[]
  warnings: string[]
}

/**
 * Runs web-ext lint on the specified directory and returns detailed diagnostic reports.
 */
export async function lintExtension(sourceDir: string): Promise<DetailedLintResult> {
  try {
    const result = await webExt.cmd.lint(
      {
        sourceDir,
        selfHosted: true,
        output: 'none',
      },
      {
        shouldExitProgram: false,
      }
    )

    const errors: string[] = []
    const warnings: string[] = []
    const diagnostics: LintDiagnostic[] = []

    let errorsCount = 0
    let warningsCount = 0

    if (result && result.errors) {
      result.errors.forEach((err: any) => {
        const file = err.file || 'manifest.json'
        const line = err.line || 1
        const column = err.column || 1
        const level: 'error' | 'warning' | 'notice' = err.level === 'error' ? 'error' : 'warning'

        const diagnostic: LintDiagnostic = {
          code: err.code || err.rule,
          message: err.message,
          file,
          line,
          column,
          level,
          description: err.description,
        }

        diagnostics.push(diagnostic)

        const formattedMsg = `[${level.toUpperCase()}] ${err.message} (${file}:${line}:${column})`
        if (level === 'error') {
          errorsCount++
          errors.push(formattedMsg)
        } else {
          warningsCount++
          warnings.push(formattedMsg)
        }
      })
    }

    return {
      success: errorsCount === 0,
      errorsCount,
      warningsCount,
      diagnostics,
      errors,
      warnings,
    }
  } catch (error: any) {
    console.error('web-ext lint failed:', error)
    return {
      success: false,
      errorsCount: 1,
      warningsCount: 0,
      diagnostics: [
        {
          message: error.message || 'web-ext lint execution failed',
          file: 'manifest.json',
          line: 1,
          column: 1,
          level: 'error',
        },
      ],
      errors: [error.message || 'web-ext lint execution failed'],
      warnings: [],
    }
  }
}

/**
 * Runs web-ext build on the specified directory, saving the zip file in the outputDir.
 * Returns the absolute path of the generated zip file.
 */
export async function buildExtension(sourceDir: string, artifactsDir: string): Promise<string> {
  try {
    // Ensure artifacts directory exists
    fs.mkdirSync(artifactsDir, { recursive: true })

    const result = await webExt.cmd.build(
      {
        sourceDir,
        artifactsDir,
        overwriteDest: true,
      },
      {
        shouldExitProgram: false,
      }
    )

    // The result contains the absolute path to the extension zip file
    if (result && result.extensionZip) {
      return result.extensionZip
    }

    // Fallback search in artifactsDir if the property name differs
    const files = fs.readdirSync(artifactsDir)
    const zipFile = files.find((f) => f.endsWith('.zip'))
    if (zipFile) {
      return path.join(artifactsDir, zipFile)
    }

    throw new Error('No zip file was generated by web-ext build')
  } catch (error: any) {
    console.error('web-ext build failed:', error)
    throw new Error(`web-ext build failed: ${error.message}`)
  }
}
